# Give Gradle enough memory to process Java 25 structures
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Core Engine Properties
minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Identity
mod_version=1.0.0
maven_group=com.example

# Updated Dependencies for 26.1.2 Architecture
fabric_api_version=0.149.1+26.1.2